name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "REACT_APP_TMDB_API_KEY=${{ secrets.REACT_APP_TMDB_API_KEY }}" >> .env

      - name: Load .env file
        run: |
          export $(cat .env | xargs)

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        run: |
          npm run build
          pwd